# docker compose up -d
# docker compose down
services:
  postgresql:
    image: postgres:12
    container_name: postgres
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: java-app
    depends_on:
      - postgresql
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge