spring.application.name=openshift-from-zero

# DB connection
spring.datasource.url=jdbc:postgresql://postgresql:5432/test
spring.datasource.username=user
spring.datasource.password=password

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Swagger
springdoc.api-docs.path=/v1/api-docs
springdoc.swagger-ui.path=/swagger-ui.html